/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Fingerprint */

#ifndef _Included_Fingerprint
#define _Included_Fingerprint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Fingerprint
 * Method:    getFingerprintCXX
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_Fingerprint_getFingerprintCXX
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
